const DEFAULTS={heroImage:"",phone:"+38 (___) ___-__-__",events:[{name:"Конференція",desc:"Діловий простір із технічним супроводом",image:""},{name:"Бізнес-форум",desc:"Великий формат, сцена, звук та кава-брейки",image:""},{name:"Весілля",desc:"Святкування з атмосферою Карпат",image:""},{name:"День народження",desc:"Особливий сценарій для вашого дня",image:""},{name:"Корпоратив",desc:"Командні події та вечірні програми",image:""},{name:"Ретрит і тренінг",desc:"Навчання, відновлення та робота команди",image:""}],packages:[{name:"Мінімальний",price:1250,tag:"Базова організація",items:["Оренда зали до 6 годин","Стандартна розстановка меблів","Екран або проєктор","Базове меню","Обслуговування персоналом","Фінальне прибирання"]},{name:"Медіум",price:1850,tag:"Оптимальний вибір",items:["Усе з пакета Мінімальний","Розширене меню","Кава-брейк або welcome-зона","Звук та два мікрофони","Базове оформлення простору","Персональний координатор"]},{name:"Преміум",price:2750,tag:"Подія під ключ",items:["Усе з пакета Медіум","Преміальне меню","Індивідуальна концепція події","Розширене технічне забезпечення","Декор і фотозона","Координація у день події"]}],extras:[{name:"Декор",price:25000},{name:"DJ та звук",price:18000},{name:"Фотозона",price:12000},{name:"Ведучий",price:20000},{name:"Трансфер",price:8000},{name:"SPA для гостей",price:15000}],gallery:["","","","","",""],benefits:["Готель і проживання","Ресторанне обслуговування","SPA та басейн","Паркінг","Професійний звук","Генератор та укриття","Трансфер","Персональний координатор"]};
let cfg=JSON.parse(localStorage.getItem('podgoreConfig')||'null')||structuredClone(DEFAULTS);
const $=s=>document.querySelector(s);
$('#loginBtn').onclick=()=>{if($('#password').value==='podgore-admin'){localStorage.setItem('podgoreAuth','1');show()}else $('#loginError').textContent='Невірний пароль'};if(localStorage.getItem('podgoreAuth')==='1')show();
function show(){$('#login').classList.add('hidden');$('#dashboard').classList.remove('hidden');render()}
document.querySelectorAll('.navbtn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.navbtn').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.tab').forEach(x=>x.classList.add('hidden'));$('#'+b.dataset.tab).classList.remove('hidden')});
function render(){
 $('#packageEditor').innerHTML=cfg.packages.map((p,i)=>`<div class="editor-row"><input data-p="name" data-i="${i}" value="${p.name}"><input data-p="price" data-i="${i}" type="number" value="${p.price}"></div><input data-p="tag" data-i="${i}" value="${p.tag}"><textarea class="items" data-p="items" data-i="${i}">${p.items.join('\n')}</textarea>`).join('<hr>');
 $('#extrasEditor').innerHTML=cfg.extras.map((x,i)=>`<div class="editor-row"><input data-e="name" data-i="${i}" value="${x.name}"><input data-e="price" data-i="${i}" type="number" value="${x.price}"></div>`).join('');
 $('#eventsEditor').innerHTML=cfg.events.map((x,i)=>`<div class="editor-event"><input data-v="name" data-i="${i}" value="${x.name}"><input data-v="desc" data-i="${i}" value="${x.desc}"></div>`).join('');
 $('#heroPreview').style.backgroundImage=cfg.heroImage?`url(${cfg.heroImage})`:'';$('#galleryPreview').innerHTML=cfg.gallery.map(x=>`<div style="background-image:url(${x})"></div>`).join('');
 const leads=JSON.parse(localStorage.getItem('podgoreLeads')||'[]');$('#leadList').innerHTML=leads.length?leads.map(l=>`<div class="lead"><strong>${l.name||'Без імені'} · ${l.phone||''}</strong><span>${l.date||'Дата не вказана'} · ${l.guests||''} гостей</span><span>${l.comment||''}</span></div>`).join(''):'Заявок ще немає.';
}
$('#save').onclick=()=>{document.querySelectorAll('[data-p]').forEach(x=>{const i=+x.dataset.i,k=x.dataset.p;cfg.packages[i][k]=k==='price'?+x.value:k==='items'?x.value.split('\n').filter(Boolean):x.value});document.querySelectorAll('[data-e]').forEach(x=>{const i=+x.dataset.i,k=x.dataset.e;cfg.extras[i][k]=k==='price'?+x.value:x.value});document.querySelectorAll('[data-v]').forEach(x=>cfg.events[+x.dataset.i][x.dataset.v]=x.value);localStorage.setItem('podgoreConfig',JSON.stringify(cfg));alert('Зміни збережено')};
const read=f=>new Promise(r=>{const fr=new FileReader();fr.onload=()=>r(fr.result);fr.readAsDataURL(f)});
$('#heroUpload').onchange=async e=>{if(e.target.files[0]){cfg.heroImage=await read(e.target.files[0]);render()}};
$('#galleryUpload').onchange=async e=>{const fs=[...e.target.files].slice(0,6);cfg.gallery=await Promise.all(fs.map(read));while(cfg.gallery.length<6)cfg.gallery.push('');render()};
